#%RAML 1.0 NamedExample
{
    "address": "lalit mitra lane",
    "pincode": "700004",
    "phoneNumber": "7980839906",
    "cardDetails": {
        "bankName": "PNB",
        "cardNumber": "1111222233334444"
    }
}